/* File generated by tracegen, do not edit */
#include "ut_omrti.h"



#define UT_TRACE_VERSION 8
UtTraceVersionInfo omrti_UtTraceVersionInfo = {UT_TRACE_VERSION};
#if defined(UT_TRACE_ENABLED_IN_BUILD)
unsigned char omrti_UtActive[14] = { 
	0,0,0,0,0,0,0,0,0,0,0,0,0,0};

unsigned char omrti_UtLevels[14] = { 
	1,1,1,1,1,1,1,1,5,5,3,3,3,3};


int32_t omrti_tpids6[] = {

	8,9	};

UtGroupDetails omrti_group6 = {
	(char *)"perfmon",
	2,
	omrti_tpids6,
	NULL};
int32_t omrti_tpids5[] = {

	1,2,3,4,5	};

UtGroupDetails omrti_group5 = {
	(char *)"Exit-Exception",
	5,
	omrti_tpids5,
	&omrti_group6};

UtGroupDetails omrti_group4 = {
	(char *)"Debug",
	0,
	NULL,
	&omrti_group5};
int32_t omrti_tpids3[] = {

	6,12	};

UtGroupDetails omrti_group3 = {
	(char *)"Exception",
	2,
	omrti_tpids3,
	&omrti_group4};
int32_t omrti_tpids2[] = {

	8,9,10,11,13	};

UtGroupDetails omrti_group2 = {
	(char *)"Event",
	5,
	omrti_tpids2,
	&omrti_group3};
int32_t omrti_tpids1[] = {

	7	};

UtGroupDetails omrti_group1 = {
	(char *)"Exit",
	1,
	omrti_tpids1,
	&omrti_group2};
int32_t omrti_tpids0[] = {

	0	};

UtGroupDetails omrti_group0 = {
	(char *)"Entry",
	1,
	omrti_tpids0,
	&omrti_group1};
UtModuleInfo omrti_UtModuleInfo = {(char*) "omrti", 5, 14, 0, omrti_UtActive , NULL, NULL, &omrti_UtTraceVersionInfo, (char*) "OMRTraceFormat.dat", omrti_UtLevels, &omrti_group0, NULL, NULL, 0, 0};

#else
unsigned char omrti_UtActive[1];
UtModuleInfo omrti_UtModuleInfo = {(char*) "omrti", 5, 0, 0, NULL, NULL, NULL, &omrti_UtTraceVersionInfo, (char*) "OMRTraceFormat.dat", NULL, NULL, NULL, NULL, 0, 0};

#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */

#if defined(UT_DIRECT_TRACE_REGISTRATION)

/* function to register with trace engine and configure current module */
int32_t
registeromrtiWithTrace(UtInterface *utIntf, UtModuleInfo * containerModule)
{
	I_32 rc = 0;

#if defined(UT_TRACE_ENABLED_IN_BUILD)

	omrti_UtModuleInfo.containerModule = containerModule;

	if( utIntf == NULL ) {
		rc = -1;
	}

	if (rc == 0) {
		utIntf->module->TraceInit(NULL, &omrti_UtModuleInfo);
	}

#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

/* function to deregister with trace engine and configure current module */
int32_t
deregisteromrtiWithTrace(UtInterface *utIntf)
{
	I_32 rc = 0;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	if( utIntf == NULL ) {
		rc = -1;
	}

	if (rc == 0) {
		utIntf->module->TraceTerm(NULL, &omrti_UtModuleInfo);
	}
#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

#else /* defined(UT_DIRECT_TRACE_REGISTRATION) */

/* function to register with trace engine and configure current module */
int32_t
registeromrtiWithTrace(JavaVM *vm, UtModuleInfo * containerModule)
{
	I_32 rc = JNI_OK;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	UtInterface *utIntf;

	omrti_UtModuleInfo.containerModule = containerModule;

	if( vm != NULL ) {
		rc = (*vm)->GetEnv(vm, (void**)&utIntf, UTE_VERSION_1_1);
	} else {
		rc = JNI_ERR;
	}

	if (rc == JNI_OK) {
		utIntf->module->TraceInit(NULL, &omrti_UtModuleInfo);
	}

#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

/* function to deregister with trace engine and configure current module */
int32_t
deregisteromrtiWithTrace(JavaVM *vm)
{
	I_32 rc = JNI_OK;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	UtInterface *utIntf;

	if( vm != NULL ) {
		rc = (*vm)->GetEnv(vm, (void**)&utIntf, UTE_VERSION_1_1);
	} else {
		rc = JNI_ERR;
	}

	if (rc == JNI_OK) {
		utIntf->module->TraceTerm(NULL, &omrti_UtModuleInfo);
	}
#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

#endif /* defined(UT_DIRECT_TRACE_REGISTRATION) */

/* End of generated file */
