/* File generated by tracegen, do not edit */
#include "ut_j9thr.h"



#define UT_TRACE_VERSION 8
UtTraceVersionInfo j9thr_UtTraceVersionInfo = {UT_TRACE_VERSION};
#if defined(UT_TRACE_ENABLED_IN_BUILD)
unsigned char j9thr_UtActive[38] = { 
	0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0};

unsigned char j9thr_UtLevels[38] = { 
	1,3,3,3,3,1,3,3,3,3,3,3,3,3,3,3,3,3,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,1,1,1,1,3};


int32_t j9thr_tpids5[] = {

	5	};

UtGroupDetails j9thr_group5 = {
	(char *)"Assertion",
	1,
	j9thr_tpids5,
	NULL};

UtGroupDetails j9thr_group4 = {
	(char *)"Debug",
	0,
	NULL,
	&j9thr_group5};
int32_t j9thr_tpids3[] = {

	18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36	};

UtGroupDetails j9thr_group3 = {
	(char *)"Exception",
	19,
	j9thr_tpids3,
	&j9thr_group4};
int32_t j9thr_tpids2[] = {

	0,1,2,3,4,8,10,14,15,16,17,37	};

UtGroupDetails j9thr_group2 = {
	(char *)"Event",
	12,
	j9thr_tpids2,
	&j9thr_group3};
int32_t j9thr_tpids1[] = {

	7,11,13	};

UtGroupDetails j9thr_group1 = {
	(char *)"Exit",
	3,
	j9thr_tpids1,
	&j9thr_group2};
int32_t j9thr_tpids0[] = {

	6,9,12	};

UtGroupDetails j9thr_group0 = {
	(char *)"Entry",
	3,
	j9thr_tpids0,
	&j9thr_group1};
UtModuleInfo j9thr_UtModuleInfo = {(char*) "j9thr", 5, 38, 0, j9thr_UtActive , NULL, NULL, &j9thr_UtTraceVersionInfo, (char*) "J9TraceFormat.dat", j9thr_UtLevels, &j9thr_group0, NULL, NULL, 0, 0};

#else
unsigned char j9thr_UtActive[1];
UtModuleInfo j9thr_UtModuleInfo = {(char*) "j9thr", 5, 0, 0, NULL, NULL, NULL, &j9thr_UtTraceVersionInfo, (char*) "J9TraceFormat.dat", NULL, NULL, NULL, NULL, 0, 0};

#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */

#if defined(UT_DIRECT_TRACE_REGISTRATION)

/* function to register with trace engine and configure current module */
int32_t
registerj9thrWithTrace(UtInterface *utIntf, UtModuleInfo * containerModule)
{
	I_32 rc = 0;

#if defined(UT_TRACE_ENABLED_IN_BUILD)

	j9thr_UtModuleInfo.containerModule = containerModule;

	if( utIntf == NULL ) {
		rc = -1;
	}

	if (rc == 0) {
		utIntf->module->TraceInit(NULL, &j9thr_UtModuleInfo);
	}

#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

/* function to deregister with trace engine and configure current module */
int32_t
deregisterj9thrWithTrace(UtInterface *utIntf)
{
	I_32 rc = 0;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	if( utIntf == NULL ) {
		rc = -1;
	}

	if (rc == 0) {
		utIntf->module->TraceTerm(NULL, &j9thr_UtModuleInfo);
	}
#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

#else /* defined(UT_DIRECT_TRACE_REGISTRATION) */

/* function to register with trace engine and configure current module */
int32_t
registerj9thrWithTrace(JavaVM *vm, UtModuleInfo * containerModule)
{
	I_32 rc = JNI_OK;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	UtInterface *utIntf;

	j9thr_UtModuleInfo.containerModule = containerModule;

	if( vm != NULL ) {
		rc = (*vm)->GetEnv(vm, (void**)&utIntf, UTE_VERSION_1_1);
	} else {
		rc = JNI_ERR;
	}

	if (rc == JNI_OK) {
		utIntf->module->TraceInit(NULL, &j9thr_UtModuleInfo);
	}

#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

/* function to deregister with trace engine and configure current module */
int32_t
deregisterj9thrWithTrace(JavaVM *vm)
{
	I_32 rc = JNI_OK;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	UtInterface *utIntf;

	if( vm != NULL ) {
		rc = (*vm)->GetEnv(vm, (void**)&utIntf, UTE_VERSION_1_1);
	} else {
		rc = JNI_ERR;
	}

	if (rc == JNI_OK) {
		utIntf->module->TraceTerm(NULL, &j9thr_UtModuleInfo);
	}
#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

#endif /* defined(UT_DIRECT_TRACE_REGISTRATION) */

/* End of generated file */
