/* File generated by tracegen, do not edit */
#include "ut_pool.h"



#define UT_TRACE_VERSION 8
UtTraceVersionInfo pool_UtTraceVersionInfo = {UT_TRACE_VERSION};
#if defined(UT_TRACE_ENABLED_IN_BUILD)
unsigned char pool_UtActive[65] = { 
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0};

unsigned char pool_UtLevels[65] = { 
	3,1,3,3,3,4,4,4,1,4,4,4,4,4,4,1,4,4,4,4,4,4,3,1,3,3,3,3,1,3,
	3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,1,1,1,1,1,1,3,3,1,
	1,1,1,1,1};



UtGroupDetails pool_group4 = {
	(char *)"Debug",
	0,
	NULL,
	NULL};
int32_t pool_tpids3[] = {

	8,15,23,28	};

UtGroupDetails pool_group3 = {
	(char *)"Exception",
	4,
	pool_tpids3,
	&pool_group4};
int32_t pool_tpids2[] = {

	56	};

UtGroupDetails pool_group2 = {
	(char *)"Event",
	1,
	pool_tpids2,
	&pool_group3};
int32_t pool_tpids1[] = {

	1,2,4,6,9,11,13,16,17,19,20,21,24,26,29,31,33,35,36,38,39,40,41,42,43,44,46,47,48,49,
	51,52,53,54,55,58,59,60,61,62,63,64	};

UtGroupDetails pool_group1 = {
	(char *)"Exit",
	42,
	pool_tpids1,
	&pool_group2};
int32_t pool_tpids0[] = {

	0,3,5,7,10,12,14,18,22,25,27,30,32,34,37,45,50,57	};

UtGroupDetails pool_group0 = {
	(char *)"Entry",
	18,
	pool_tpids0,
	&pool_group1};
UtModuleInfo pool_UtModuleInfo = {(char*) "pool", 4, 65, 0, pool_UtActive , NULL, NULL, &pool_UtTraceVersionInfo, (char*) "J9TraceFormat.dat", pool_UtLevels, &pool_group0, NULL, NULL, 0, 0};

#else
unsigned char pool_UtActive[1];
UtModuleInfo pool_UtModuleInfo = {(char*) "pool", 4, 0, 0, NULL, NULL, NULL, &pool_UtTraceVersionInfo, (char*) "J9TraceFormat.dat", NULL, NULL, NULL, NULL, 0, 0};

#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */

#if defined(UT_DIRECT_TRACE_REGISTRATION)

/* function to register with trace engine and configure current module */
int32_t
registerpoolWithTrace(UtInterface *utIntf, UtModuleInfo * containerModule)
{
	I_32 rc = 0;

#if defined(UT_TRACE_ENABLED_IN_BUILD)

	pool_UtModuleInfo.containerModule = containerModule;

	if( utIntf == NULL ) {
		rc = -1;
	}

	if (rc == 0) {
		utIntf->module->TraceInit(NULL, &pool_UtModuleInfo);
	}

#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

/* function to deregister with trace engine and configure current module */
int32_t
deregisterpoolWithTrace(UtInterface *utIntf)
{
	I_32 rc = 0;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	if( utIntf == NULL ) {
		rc = -1;
	}

	if (rc == 0) {
		utIntf->module->TraceTerm(NULL, &pool_UtModuleInfo);
	}
#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

#else /* defined(UT_DIRECT_TRACE_REGISTRATION) */

/* function to register with trace engine and configure current module */
int32_t
registerpoolWithTrace(JavaVM *vm, UtModuleInfo * containerModule)
{
	I_32 rc = JNI_OK;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	UtInterface *utIntf;

	pool_UtModuleInfo.containerModule = containerModule;

	if( vm != NULL ) {
		rc = (*vm)->GetEnv(vm, (void**)&utIntf, UTE_VERSION_1_1);
	} else {
		rc = JNI_ERR;
	}

	if (rc == JNI_OK) {
		utIntf->module->TraceInit(NULL, &pool_UtModuleInfo);
	}

#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

/* function to deregister with trace engine and configure current module */
int32_t
deregisterpoolWithTrace(JavaVM *vm)
{
	I_32 rc = JNI_OK;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	UtInterface *utIntf;

	if( vm != NULL ) {
		rc = (*vm)->GetEnv(vm, (void**)&utIntf, UTE_VERSION_1_1);
	} else {
		rc = JNI_ERR;
	}

	if (rc == JNI_OK) {
		utIntf->module->TraceTerm(NULL, &pool_UtModuleInfo);
	}
#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

#endif /* defined(UT_DIRECT_TRACE_REGISTRATION) */

/* End of generated file */
