/* File generated by tracegen, do not edit */
#include "ut_j9vgc.h"



#define UT_TRACE_VERSION 8
UtTraceVersionInfo j9vgc_UtTraceVersionInfo = {UT_TRACE_VERSION};
#if defined(UT_TRACE_ENABLED_IN_BUILD)
unsigned char j9vgc_UtActive[3] = { 
	0,1,1};

unsigned char j9vgc_UtLevels[3] = { 
	3,1,1};


int32_t j9vgc_tpids5[] = {

	1,2	};

UtGroupDetails j9vgc_group5 = {
	(char *)"Assertion",
	2,
	j9vgc_tpids5,
	NULL};

UtGroupDetails j9vgc_group4 = {
	(char *)"Debug",
	0,
	NULL,
	&j9vgc_group5};

UtGroupDetails j9vgc_group3 = {
	(char *)"Exception",
	0,
	NULL,
	&j9vgc_group4};
int32_t j9vgc_tpids2[] = {

	0	};

UtGroupDetails j9vgc_group2 = {
	(char *)"Event",
	1,
	j9vgc_tpids2,
	&j9vgc_group3};

UtGroupDetails j9vgc_group1 = {
	(char *)"Exit",
	0,
	NULL,
	&j9vgc_group2};

UtGroupDetails j9vgc_group0 = {
	(char *)"Entry",
	0,
	NULL,
	&j9vgc_group1};
UtModuleInfo j9vgc_UtModuleInfo = {(char*) "j9vgc", 5, 3, 0, j9vgc_UtActive , NULL, NULL, &j9vgc_UtTraceVersionInfo, (char*) "J9TraceFormat.dat", j9vgc_UtLevels, &j9vgc_group0, NULL, NULL, 0, 0};

#else
unsigned char j9vgc_UtActive[1];
UtModuleInfo j9vgc_UtModuleInfo = {(char*) "j9vgc", 5, 0, 0, NULL, NULL, NULL, &j9vgc_UtTraceVersionInfo, (char*) "J9TraceFormat.dat", NULL, NULL, NULL, NULL, 0, 0};

#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */

#if defined(UT_DIRECT_TRACE_REGISTRATION)

/* function to register with trace engine and configure current module */
int32_t
registerj9vgcWithTrace(UtInterface *utIntf, UtModuleInfo * containerModule)
{
	I_32 rc = 0;

#if defined(UT_TRACE_ENABLED_IN_BUILD)

	j9vgc_UtModuleInfo.containerModule = containerModule;

	if( utIntf == NULL ) {
		rc = -1;
	}

	if (rc == 0) {
		utIntf->module->TraceInit(NULL, &j9vgc_UtModuleInfo);
	}

#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

/* function to deregister with trace engine and configure current module */
int32_t
deregisterj9vgcWithTrace(UtInterface *utIntf)
{
	I_32 rc = 0;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	if( utIntf == NULL ) {
		rc = -1;
	}

	if (rc == 0) {
		utIntf->module->TraceTerm(NULL, &j9vgc_UtModuleInfo);
	}
#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

#else /* defined(UT_DIRECT_TRACE_REGISTRATION) */

/* function to register with trace engine and configure current module */
int32_t
registerj9vgcWithTrace(JavaVM *vm, UtModuleInfo * containerModule)
{
	I_32 rc = JNI_OK;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	UtInterface *utIntf;

	j9vgc_UtModuleInfo.containerModule = containerModule;

	if( vm != NULL ) {
		rc = (*vm)->GetEnv(vm, (void**)&utIntf, UTE_VERSION_1_1);
	} else {
		rc = JNI_ERR;
	}

	if (rc == JNI_OK) {
		utIntf->module->TraceInit(NULL, &j9vgc_UtModuleInfo);
	}

#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

/* function to deregister with trace engine and configure current module */
int32_t
deregisterj9vgcWithTrace(JavaVM *vm)
{
	I_32 rc = JNI_OK;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	UtInterface *utIntf;

	if( vm != NULL ) {
		rc = (*vm)->GetEnv(vm, (void**)&utIntf, UTE_VERSION_1_1);
	} else {
		rc = JNI_ERR;
	}

	if (rc == JNI_OK) {
		utIntf->module->TraceTerm(NULL, &j9vgc_UtModuleInfo);
	}
#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

#endif /* defined(UT_DIRECT_TRACE_REGISTRATION) */

/* End of generated file */
