/*
 *  Do not edit this file 
 *  Generated by TraceGen
 */
#ifndef UTE_J9VGC_MODULE_HEADER
#define UTE_J9VGC_MODULE_HEADER
#include "ute_module.h"
#if !defined(UT_DIRECT_TRACE_REGISTRATION)
#include "jni.h"
#endif /* !defined(UT_DIRECT_TRACE_REGISTRATION) */
#ifndef UT_TRACE_OVERHEAD
#define UT_TRACE_OVERHEAD 1
#endif
#ifndef UT_THREAD
#define UT_THREAD(thr) (void *)thr
#endif /* UT_THREAD */
#ifndef UT_STR
#define UT_STR(arg) #arg
#endif
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __clang__
#include <unistd.h>
#define Trace_Unreachable() _exit(-1)
#else
#define Trace_Unreachable()
#endif

#if defined(UT_DIRECT_TRACE_REGISTRATION)
int32_t registerj9vgcWithTrace(UtInterface * utIntf, UtModuleInfo* containerName);
int32_t deregisterj9vgcWithTrace(UtInterface * utIntf);
#define UT_MODULE_LOADED(utIntf) registerj9vgcWithTrace((utIntf), NULL);
#define UT_MODULE_UNLOADED(utIntf) deregisterj9vgcWithTrace((utIntf));
#define UT_J9VGC_MODULE_LOADED(utIntf) registerj9vgcWithTrace((utIntf), NULL);
#define UT_J9VGC_MODULE_UNLOADED(utIntf) deregisterj9vgcWithTrace((utIntf));
#else /* defined(UT_DIRECT_TRACE_REGISTRATION) */
int32_t registerj9vgcWithTrace(JavaVM * vm, UtModuleInfo* containerName);
int32_t deregisterj9vgcWithTrace(JavaVM * vm);
#define UT_MODULE_LOADED(vm) registerj9vgcWithTrace((JavaVM *)(vm), NULL);
#define UT_MODULE_UNLOADED(vm) deregisterj9vgcWithTrace((JavaVM *)(vm));
#define UT_J9VGC_MODULE_LOADED(vm) registerj9vgcWithTrace((JavaVM *)(vm), NULL);
#define UT_J9VGC_MODULE_UNLOADED(vm) deregisterj9vgcWithTrace((JavaVM *)(vm));
#endif /* defined(UT_DIRECT_TRACE_REGISTRATION) */

#if UT_TRACE_OVERHEAD >= 1
#define Trc_VGC_Verbosegc(thr, P1) do { /* tracepoint name: j9vgc.0 */ \
	if ((unsigned char) j9vgc_UtActive[0] != 0){ \
		j9vgc_UtModuleInfo.intf->Trace(UT_THREAD(thr), &j9vgc_UtModuleInfo, ((0u << 8) | j9vgc_UtActive[0]), "\377", P1);} \
	} while(0)
#else
#define Trc_VGC_Verbosegc(thr, P1)   /* tracepoint name: j9vgc.0 */
#endif

#if UT_TRACE_OVERHEAD >= 1
#define Assert_VGC_true(P1) do { /* tracepoint name: j9vgc.1 */ \
	if ((unsigned char) j9vgc_UtActive[1] != 0){ \
		if ((P1)) { /* assertion satisfied */ } else { \
			if (j9vgc_UtModuleInfo.intf != NULL) { \
				j9vgc_UtModuleInfo.intf->Trace((void *)NULL, &j9vgc_UtModuleInfo, (UT_SPECIAL_ASSERTION | (1u << 8) | j9vgc_UtActive[1]), "\377\4\377", __FILE__, __LINE__, UT_STR(((P1)))); \
				Trace_Unreachable(); \
			} else { \
				fprintf(stderr, "** ASSERTION FAILED ** j9vgc.1 at %s:%d Assert_VGC_true%s\n", __FILE__, __LINE__, UT_STR(((P1)))); \
			} \
		}} \
	} while(0)
#else
#define Assert_VGC_true(P1)   /* tracepoint name: j9vgc.1 */
#endif

#if UT_TRACE_OVERHEAD >= 1
#define Assert_VGC_false(P1) do { /* tracepoint name: j9vgc.2 */ \
	if ((unsigned char) j9vgc_UtActive[2] != 0){ \
		if (!(P1)) { /* assertion satisfied */ } else { \
			if (j9vgc_UtModuleInfo.intf != NULL) { \
				j9vgc_UtModuleInfo.intf->Trace((void *)NULL, &j9vgc_UtModuleInfo, (UT_SPECIAL_ASSERTION | (2u << 8) | j9vgc_UtActive[2]), "\377\4\377", __FILE__, __LINE__, UT_STR((!(P1)))); \
				Trace_Unreachable(); \
			} else { \
				fprintf(stderr, "** ASSERTION FAILED ** j9vgc.2 at %s:%d Assert_VGC_false%s\n", __FILE__, __LINE__, UT_STR((!(P1)))); \
			} \
		}} \
	} while(0)
#else
#define Assert_VGC_false(P1)   /* tracepoint name: j9vgc.2 */
#endif

extern UtModuleInfo j9vgc_UtModuleInfo;
extern unsigned char j9vgc_UtActive[];

#ifndef UT_MODULE_INFO
#define UT_MODULE_INFO j9vgc_UtModuleInfo
#endif /* UT_MODULE_INFO */

#ifndef UT_ACTIVE
#define UT_ACTIVE j9vgc_UtActive
#endif /* UT_ACTIVE */

#ifdef __cplusplus
} /* extern "C" */
#endif
#endif /* UTE_J9VGC_MODULE_HEADER */
/*
 * End of file
 */
