/* File generated by tracegen, do not edit */
#include "ut_j9mm.h"



#define UT_TRACE_VERSION 8
UtTraceVersionInfo j9mm_UtTraceVersionInfo = {UT_TRACE_VERSION};
#if defined(UT_TRACE_ENABLED_IN_BUILD)
unsigned char j9mm_UtActive[655] = { 
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,
	0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0};

unsigned char j9mm_UtLevels[655] = { 
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,1,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,4,6,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9,1,1,
	1,9,9,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9,9,1,9,9,9,9,1,1,1,9,
	9,9,1,1,9,9,1,1,1,1,9,9,9,9,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,3,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,9,9,9,9,9,9,1,1,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,4,4,4,4,1,1,1,1,1,1,
	1,1,1,1,1,1,1,1,1,1,1,9,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,4,3,3,1,1,1,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,4,4,4,1,1,1,1,1,1,1,1,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,4,1,1,1,1,1,1,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,
	1,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,1,1,1,1,
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
	1,1,1,1,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,1,4,1,2,1,1,1,1,4,
	9,9,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2};


int32_t j9mm_tpids35[] = {

	579,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619	};

UtGroupDetails j9mm_group35 = {
	(char *)"alloclarge",
	17,
	j9mm_tpids35,
	NULL};
int32_t j9mm_tpids34[] = {

	570,571,572,573,574,575,576	};

UtGroupDetails j9mm_group34 = {
	(char *)"aging",
	7,
	j9mm_tpids34,
	&j9mm_group35};
int32_t j9mm_tpids33[] = {

	563,564,565,566	};

UtGroupDetails j9mm_group33 = {
	(char *)"ageblending",
	4,
	j9mm_tpids33,
	&j9mm_group34};
int32_t j9mm_tpids32[] = {

	545,546,547,548,549,550,551,552,553,554,555,556	};

UtGroupDetails j9mm_group32 = {
	(char *)"parallel",
	12,
	j9mm_tpids32,
	&j9mm_group33};
int32_t j9mm_tpids31[] = {

	538,539,540,541,627	};

UtGroupDetails j9mm_group31 = {
	(char *)"scavenger",
	5,
	j9mm_tpids31,
	&j9mm_group32};
int32_t j9mm_tpids30[] = {

	520,521,522,523,524,525,625,626,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651	};

UtGroupDetails j9mm_group30 = {
	(char *)"runtimeexec",
	27,
	j9mm_tpids30,
	&j9mm_group31};
int32_t j9mm_tpids29[] = {

	499,500,501,502,503,504	};

UtGroupDetails j9mm_group29 = {
	(char *)"regionvalidator",
	6,
	j9mm_tpids29,
	&j9mm_group30};
int32_t j9mm_tpids28[] = {

	491,502	};

UtGroupDetails j9mm_group28 = {
	(char *)"Exit-Exception",
	2,
	j9mm_tpids28,
	&j9mm_group29};
int32_t j9mm_tpids27[] = {

	480,499	};

UtGroupDetails j9mm_group27 = {
	(char *)"Entry-Exception",
	2,
	j9mm_tpids27,
	&j9mm_group28};
int32_t j9mm_tpids26[] = {

	479,480,481,482,483,484,485,486,487,488,489,490,491,493	};

UtGroupDetails j9mm_group26 = {
	(char *)"stackslotvalidator",
	14,
	j9mm_tpids26,
	&j9mm_group27};
int32_t j9mm_tpids25[] = {

	389,390	};

UtGroupDetails j9mm_group25 = {
	(char *)"cardscrubbing",
	2,
	j9mm_tpids25,
	&j9mm_group26};
int32_t j9mm_tpids24[] = {

	385,386,387	};

UtGroupDetails j9mm_group24 = {
	(char *)"markdelegate",
	3,
	j9mm_tpids24,
	&j9mm_group25};
int32_t j9mm_tpids23[] = {

	357,367,369,370,371,372,441,507,508,509,510,511	};

UtGroupDetails j9mm_group23 = {
	(char *)"copyforwardscheme",
	12,
	j9mm_tpids23,
	&j9mm_group24};
int32_t j9mm_tpids22[] = {

	353,354,355,356,623	};

UtGroupDetails j9mm_group22 = {
	(char *)"stringtable",
	5,
	j9mm_tpids22,
	&j9mm_group23};
int32_t j9mm_tpids21[] = {

	339,340,341,342,343,344,351,352,391,451,452,453,454,544	};

UtGroupDetails j9mm_group21 = {
	(char *)"dynamiccollectionset",
	14,
	j9mm_tpids21,
	&j9mm_group22};
int32_t j9mm_tpids20[] = {

	329,330,331,360,361,526,527,528,529	};

UtGroupDetails j9mm_group20 = {
	(char *)"rememberedset",
	9,
	j9mm_tpids20,
	&j9mm_group21};
int32_t j9mm_tpids19[] = {

	311	};

UtGroupDetails j9mm_group19 = {
	(char *)"darkMatterComparison",
	1,
	j9mm_tpids19,
	&j9mm_group20};
int32_t j9mm_tpids18[] = {

	296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,312,313,314,362,363,364,365,366,373,377,455,456,457,458,459,
	460,461,462,472,473,557,567,568,569,577	};

UtGroupDetails j9mm_group18 = {
	(char *)"reclaim",
	40,
	j9mm_tpids18,
	&j9mm_group19};
int32_t j9mm_tpids17[] = {

	294,295,317,318,319,320,321,322,323,324,325,326,327,328,332,333,334,335,336,337,338,359,368,374,375,376,382,388,448,449,
	450,558,559,561,562,578	};

UtGroupDetails j9mm_group17 = {
	(char *)"kickoff",
	36,
	j9mm_tpids17,
	&j9mm_group18};
int32_t j9mm_tpids16[] = {

	281,282,283,284,289,290,291,292,293,378,379,380,381,442,443,444,445,622,629	};

UtGroupDetails j9mm_group16 = {
	(char *)"unload",
	19,
	j9mm_tpids16,
	&j9mm_group17};
int32_t j9mm_tpids15[] = {

	268,269,270,271,272,273,274,275,276,277,278,279	};

UtGroupDetails j9mm_group15 = {
	(char *)"compact",
	12,
	j9mm_tpids15,
	&j9mm_group16};
int32_t j9mm_tpids14[] = {

	247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262	};

UtGroupDetails j9mm_group14 = {
	(char *)"concurrent",
	16,
	j9mm_tpids14,
	&j9mm_group15};
int32_t j9mm_tpids13[] = {

	241,242,243,244,245,246	};

UtGroupDetails j9mm_group13 = {
	(char *)"stackremember",
	6,
	j9mm_tpids13,
	&j9mm_group14};
int32_t j9mm_tpids12[] = {

	231,232,233,234,235,236,237,238,239,240	};

UtGroupDetails j9mm_group12 = {
	(char *)"allocthreshold",
	10,
	j9mm_tpids12,
	&j9mm_group13};
int32_t j9mm_tpids11[] = {

	213,214,215,216,624	};

UtGroupDetails j9mm_group11 = {
	(char *)"arraylet",
	5,
	j9mm_tpids11,
	&j9mm_group12};
int32_t j9mm_tpids10[] = {

	194,195,228,229,230,263,264,267,280	};

UtGroupDetails j9mm_group10 = {
	(char *)"oracle",
	9,
	j9mm_tpids10,
	&j9mm_group11};
int32_t j9mm_tpids9[] = {

	186,187,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,217,218,219,220,221,222,223,224,225,226,227,
	512,513,514,515,516,517,518,519,580,582,583,584,585,586,587,593,595,596,597,598	};

UtGroupDetails j9mm_group9 = {
	(char *)"tarok",
	50,
	j9mm_tpids9,
	&j9mm_group10};
int32_t j9mm_tpids8[] = {

	107,108,141,142,160,161,189,315,316,479,620,632,652,653	};

UtGroupDetails j9mm_group8 = {
	(char *)"Assertion",
	14,
	j9mm_tpids8,
	&j9mm_group9};
int32_t j9mm_tpids7[] = {

	50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,67,68,69,70,71,72,73,74,75,76,77,78,79,80,
	81,82,83,84,85,86,90,91,94,95,96,97,98,99,100,101,102,127,128,129,131,132,133,134,135,136,137,138,139,140,
	188,345,346,347,348,358,383,384,393,463,464,465,466,467,468,469,470,471,474,475,492,506,560,621,628	};

UtGroupDetails j9mm_group7 = {
	(char *)"gclogger",
	85,
	j9mm_tpids7,
	&j9mm_group8};
int32_t j9mm_tpids6[] = {

	7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,
	37,38,39,40,41,42,43,44,45,46,47,48,92,93,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,
	412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440	};

UtGroupDetails j9mm_group6 = {
	(char *)"resize",
	89,
	j9mm_tpids6,
	&j9mm_group7};
int32_t j9mm_tpids5[] = {

	0,1,2,5,149,151,152,153,154,155,156,157,392	};

UtGroupDetails j9mm_group5 = {
	(char *)"percolate",
	13,
	j9mm_tpids5,
	&j9mm_group6};

UtGroupDetails j9mm_group4 = {
	(char *)"Debug",
	0,
	NULL,
	&j9mm_group5};
int32_t j9mm_tpids3[] = {

	127,128,129,171,176,177,178,182,183,214,215,481,482,483,484,485,486,487,488,489,490,493,494,495,496,497,498,500,501,503,
	504,506,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651	};

UtGroupDetails j9mm_group3 = {
	(char *)"Exception",
	51,
	j9mm_tpids3,
	&j9mm_group4};
int32_t j9mm_tpids2[] = {

	34,35,39,40,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,
	75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,94,95,96,97,98,99,100,101,102,113,126,130,131,
	132,133,134,135,136,137,138,139,140,143,144,149,151,152,153,154,155,156,157,164,165,166,167,168,170,181,184,188,194,195,
	196,221,222,223,224,227,228,229,230,233,234,235,236,237,238,239,240,241,242,243,244,245,246,263,264,267,268,269,270,271,
	272,273,274,275,276,277,278,279,280,285,286,287,288,291,292,297,298,299,300,301,302,303,304,307,308,309,311,313,319,320,
	324,327,329,330,331,334,336,337,339,340,341,342,343,344,345,346,347,348,351,352,355,356,357,358,359,360,361,362,363,365,
	367,368,370,371,373,374,375,376,377,380,381,382,383,384,386,388,391,392,393,394,395,416,417,421,422,429,430,431,432,433,
	434,436,437,441,446,447,449,459,461,463,464,465,466,467,468,469,470,471,474,475,477,492,505,509,510,511,513,514,515,516,
	520,521,526,527,528,529,530,531,532,533,534,535,536,537,539,540,544,545,546,547,548,549,550,551,552,553,554,555,556,558,
	559,560,561,562,563,564,565,566,567,568,569,570,572,573,575,576,577,578,579,580,581,585,588,589,590,591,592,593,594,596,
	599,600,601,602,603,605,608,611,614,615,616,617,618,621,622,623,627,628,629,630,631,654	};

UtGroupDetails j9mm_group2 = {
	(char *)"Event",
	322,
	j9mm_tpids2,
	&j9mm_group3};
int32_t j9mm_tpids1[] = {

	1,2,4,5,6,8,9,10,12,14,15,16,18,19,21,23,24,26,27,28,29,30,31,32,36,38,41,42,44,45,
	47,48,93,104,106,110,111,114,115,117,119,121,123,125,146,147,150,159,163,172,174,179,185,187,191,193,198,200,202,204,
	206,208,210,212,216,218,219,225,226,232,248,250,251,253,254,256,258,260,262,266,282,284,290,293,295,305,310,314,318,322,
	325,328,333,338,350,354,366,372,379,387,390,397,399,400,401,403,404,406,408,409,410,411,412,413,414,418,420,423,424,426,
	428,438,440,443,445,450,452,454,456,458,462,473,478,508,517,519,523,525,541,543,557,574,583,586,587,597,598,606,609,612,
	619,626	};

UtGroupDetails j9mm_group1 = {
	(char *)"Exit",
	152,
	j9mm_tpids1,
	&j9mm_group2};
int32_t j9mm_tpids0[] = {

	0,3,7,11,13,17,20,22,25,33,37,43,46,92,103,105,109,112,116,118,120,122,124,145,148,158,162,169,173,175,
	180,186,190,192,197,199,201,203,205,207,209,211,213,217,220,231,247,249,252,255,257,259,261,265,281,283,289,294,296,306,
	312,317,321,323,326,332,335,349,353,364,369,378,385,389,396,398,402,405,407,415,419,425,427,435,439,442,444,448,451,453,
	455,457,460,472,476,507,512,518,522,524,538,542,571,582,584,595,604,607,610,613,624,625	};

UtGroupDetails j9mm_group0 = {
	(char *)"Entry",
	112,
	j9mm_tpids0,
	&j9mm_group1};
UtModuleInfo j9mm_UtModuleInfo = {(char*) "j9mm", 4, 655, 0, j9mm_UtActive , NULL, NULL, &j9mm_UtTraceVersionInfo, (char*) "J9TraceFormat.dat", j9mm_UtLevels, &j9mm_group0, NULL, NULL, 0, 0};

#else
unsigned char j9mm_UtActive[1];
UtModuleInfo j9mm_UtModuleInfo = {(char*) "j9mm", 4, 0, 0, NULL, NULL, NULL, &j9mm_UtTraceVersionInfo, (char*) "J9TraceFormat.dat", NULL, NULL, NULL, NULL, 0, 0};

#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */

#if defined(UT_DIRECT_TRACE_REGISTRATION)

/* function to register with trace engine and configure current module */
int32_t
registerj9mmWithTrace(UtInterface *utIntf, UtModuleInfo * containerModule)
{
	I_32 rc = 0;

#if defined(UT_TRACE_ENABLED_IN_BUILD)

	j9mm_UtModuleInfo.containerModule = containerModule;

	if( utIntf == NULL ) {
		rc = -1;
	}

	if (rc == 0) {
		utIntf->module->TraceInit(NULL, &j9mm_UtModuleInfo);
	}

	if (rc == 0) {
		extern int32_t registerj9utilcoreWithTrace(UtInterface *utIntf, UtModuleInfo* containerModule);

		rc = registerj9utilcoreWithTrace(utIntf, &j9mm_UtModuleInfo);
	}

#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

/* function to deregister with trace engine and configure current module */
int32_t
deregisterj9mmWithTrace(UtInterface *utIntf)
{
	I_32 rc = 0;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	if( utIntf == NULL ) {
		rc = -1;
	}

	if (rc == 0) {
		utIntf->module->TraceTerm(NULL, &j9mm_UtModuleInfo);
	}

	if (rc == 0) {
		extern int32_t deregisterj9utilcoreWithTrace(UtInterface *utIntf);

		rc = deregisterj9utilcoreWithTrace(utIntf);
	}
#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

#else /* defined(UT_DIRECT_TRACE_REGISTRATION) */

/* function to register with trace engine and configure current module */
int32_t
registerj9mmWithTrace(JavaVM *vm, UtModuleInfo * containerModule)
{
	I_32 rc = JNI_OK;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	UtInterface *utIntf;

	j9mm_UtModuleInfo.containerModule = containerModule;

	if( vm != NULL ) {
		rc = (*vm)->GetEnv(vm, (void**)&utIntf, UTE_VERSION_1_1);
	} else {
		rc = JNI_ERR;
	}

	if (rc == JNI_OK) {
		utIntf->module->TraceInit(NULL, &j9mm_UtModuleInfo);
	}

	if (rc == JNI_OK) {
		extern int32_t registerj9utilcoreWithTrace(JavaVM *vm, UtModuleInfo* containerModule);

		rc = registerj9utilcoreWithTrace(vm, &j9mm_UtModuleInfo);
	}

#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

/* function to deregister with trace engine and configure current module */
int32_t
deregisterj9mmWithTrace(JavaVM *vm)
{
	I_32 rc = JNI_OK;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	UtInterface *utIntf;

	if( vm != NULL ) {
		rc = (*vm)->GetEnv(vm, (void**)&utIntf, UTE_VERSION_1_1);
	} else {
		rc = JNI_ERR;
	}

	if (rc == JNI_OK) {
		utIntf->module->TraceTerm(NULL, &j9mm_UtModuleInfo);
	}

	if (rc == JNI_OK) {
		extern int32_t deregisterj9utilcoreWithTrace(JavaVM *vm);

		rc = deregisterj9utilcoreWithTrace(vm);
	}
#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

#endif /* defined(UT_DIRECT_TRACE_REGISTRATION) */

/* End of generated file */
