/* File generated by tracegen, do not edit */
#include "ut_omrmm.h"



#define UT_TRACE_VERSION 8
UtTraceVersionInfo omrmm_UtTraceVersionInfo = {UT_TRACE_VERSION};
#if defined(UT_TRACE_ENABLED_IN_BUILD)
unsigned char omrmm_UtActive[20] = { 
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};

unsigned char omrmm_UtLevels[20] = { 
	1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1};


int32_t omrmm_tpids7[] = {

	19	};

UtGroupDetails omrmm_group7 = {
	(char *)"compact",
	1,
	omrmm_tpids7,
	NULL};
int32_t omrmm_tpids6[] = {

	2,3	};

UtGroupDetails omrmm_group6 = {
	(char *)"percolate",
	2,
	omrmm_tpids6,
	&omrmm_group7};
int32_t omrmm_tpids5[] = {

	0,1,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18	};

UtGroupDetails omrmm_group5 = {
	(char *)"gclogger",
	17,
	omrmm_tpids5,
	&omrmm_group6};

UtGroupDetails omrmm_group4 = {
	(char *)"Debug",
	0,
	NULL,
	&omrmm_group5};

UtGroupDetails omrmm_group3 = {
	(char *)"Exception",
	0,
	NULL,
	&omrmm_group4};
int32_t omrmm_tpids2[] = {

	0,1,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19	};

UtGroupDetails omrmm_group2 = {
	(char *)"Event",
	18,
	omrmm_tpids2,
	&omrmm_group3};
int32_t omrmm_tpids1[] = {

	2,3	};

UtGroupDetails omrmm_group1 = {
	(char *)"Exit",
	2,
	omrmm_tpids1,
	&omrmm_group2};

UtGroupDetails omrmm_group0 = {
	(char *)"Entry",
	0,
	NULL,
	&omrmm_group1};
UtModuleInfo omrmm_UtModuleInfo = {(char*) "omrmm", 5, 20, 0, omrmm_UtActive , NULL, NULL, &omrmm_UtTraceVersionInfo, (char*) "OMRTraceFormat.dat", omrmm_UtLevels, &omrmm_group0, NULL, NULL, 0, 0};

#else
unsigned char omrmm_UtActive[1];
UtModuleInfo omrmm_UtModuleInfo = {(char*) "omrmm", 5, 0, 0, NULL, NULL, NULL, &omrmm_UtTraceVersionInfo, (char*) "OMRTraceFormat.dat", NULL, NULL, NULL, NULL, 0, 0};

#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */

#if defined(UT_DIRECT_TRACE_REGISTRATION)

/* function to register with trace engine and configure current module */
int32_t
registeromrmmWithTrace(UtInterface *utIntf, UtModuleInfo * containerModule)
{
	I_32 rc = 0;

#if defined(UT_TRACE_ENABLED_IN_BUILD)

	omrmm_UtModuleInfo.containerModule = containerModule;

	if( utIntf == NULL ) {
		rc = -1;
	}

	if (rc == 0) {
		utIntf->module->TraceInit(NULL, &omrmm_UtModuleInfo);
	}

#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

/* function to deregister with trace engine and configure current module */
int32_t
deregisteromrmmWithTrace(UtInterface *utIntf)
{
	I_32 rc = 0;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	if( utIntf == NULL ) {
		rc = -1;
	}

	if (rc == 0) {
		utIntf->module->TraceTerm(NULL, &omrmm_UtModuleInfo);
	}
#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

#else /* defined(UT_DIRECT_TRACE_REGISTRATION) */

/* function to register with trace engine and configure current module */
int32_t
registeromrmmWithTrace(JavaVM *vm, UtModuleInfo * containerModule)
{
	I_32 rc = JNI_OK;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	UtInterface *utIntf;

	omrmm_UtModuleInfo.containerModule = containerModule;

	if( vm != NULL ) {
		rc = (*vm)->GetEnv(vm, (void**)&utIntf, UTE_VERSION_1_1);
	} else {
		rc = JNI_ERR;
	}

	if (rc == JNI_OK) {
		utIntf->module->TraceInit(NULL, &omrmm_UtModuleInfo);
	}

#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

/* function to deregister with trace engine and configure current module */
int32_t
deregisteromrmmWithTrace(JavaVM *vm)
{
	I_32 rc = JNI_OK;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	UtInterface *utIntf;

	if( vm != NULL ) {
		rc = (*vm)->GetEnv(vm, (void**)&utIntf, UTE_VERSION_1_1);
	} else {
		rc = JNI_ERR;
	}

	if (rc == JNI_OK) {
		utIntf->module->TraceTerm(NULL, &omrmm_UtModuleInfo);
	}
#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

#endif /* defined(UT_DIRECT_TRACE_REGISTRATION) */

/* End of generated file */
