/*
 *  Do not edit this file 
 *  Generated by TraceGen
 */
#ifndef UTE_HASHTABLE_MODULE_HEADER
#define UTE_HASHTABLE_MODULE_HEADER
#include "ute_module.h"
#if !defined(UT_DIRECT_TRACE_REGISTRATION)
#include "jni.h"
#endif /* !defined(UT_DIRECT_TRACE_REGISTRATION) */
#ifndef UT_TRACE_OVERHEAD
#define UT_TRACE_OVERHEAD 1
#endif
#ifndef UT_THREAD
#define UT_THREAD(thr) (void *)thr
#endif /* UT_THREAD */
#ifndef UT_STR
#define UT_STR(arg) #arg
#endif
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __clang__
#include <unistd.h>
#define Trace_Unreachable() _exit(-1)
#else
#define Trace_Unreachable()
#endif

#if defined(UT_DIRECT_TRACE_REGISTRATION)
int32_t registerhashtableWithTrace(UtInterface * utIntf, UtModuleInfo* containerName);
int32_t deregisterhashtableWithTrace(UtInterface * utIntf);
#define UT_MODULE_LOADED(utIntf) registerhashtableWithTrace((utIntf), NULL);
#define UT_MODULE_UNLOADED(utIntf) deregisterhashtableWithTrace((utIntf));
#define UT_HASHTABLE_MODULE_LOADED(utIntf) registerhashtableWithTrace((utIntf), NULL);
#define UT_HASHTABLE_MODULE_UNLOADED(utIntf) deregisterhashtableWithTrace((utIntf));
#else /* defined(UT_DIRECT_TRACE_REGISTRATION) */
int32_t registerhashtableWithTrace(JavaVM * vm, UtModuleInfo* containerName);
int32_t deregisterhashtableWithTrace(JavaVM * vm);
#define UT_MODULE_LOADED(vm) registerhashtableWithTrace((JavaVM *)(vm), NULL);
#define UT_MODULE_UNLOADED(vm) deregisterhashtableWithTrace((JavaVM *)(vm));
#define UT_HASHTABLE_MODULE_LOADED(vm) registerhashtableWithTrace((JavaVM *)(vm), NULL);
#define UT_HASHTABLE_MODULE_UNLOADED(vm) deregisterhashtableWithTrace((JavaVM *)(vm));
#endif /* defined(UT_DIRECT_TRACE_REGISTRATION) */

#if UT_TRACE_OVERHEAD >= 1
#define Assert_hashTable_true(P1) do { /* tracepoint name: hashtable.0 */ \
	if ((unsigned char) hashtable_UtActive[0] != 0){ \
		if ((P1)) { /* assertion satisfied */ } else { \
			if (hashtable_UtModuleInfo.intf != NULL) { \
				hashtable_UtModuleInfo.intf->Trace((void *)NULL, &hashtable_UtModuleInfo, (UT_SPECIAL_ASSERTION | (0u << 8) | hashtable_UtActive[0]), "\377\4\377", __FILE__, __LINE__, UT_STR(((P1)))); \
				Trace_Unreachable(); \
			} else { \
				fprintf(stderr, "** ASSERTION FAILED ** hashtable.0 at %s:%d Assert_hashTable_true%s\n", __FILE__, __LINE__, UT_STR(((P1)))); \
			} \
		}} \
	} while(0)
#else
#define Assert_hashTable_true(P1)   /* tracepoint name: hashtable.0 */
#endif

#if UT_TRACE_OVERHEAD >= 1
#define Assert_hashTable_false(P1) do { /* tracepoint name: hashtable.1 */ \
	if ((unsigned char) hashtable_UtActive[1] != 0){ \
		if (!(P1)) { /* assertion satisfied */ } else { \
			if (hashtable_UtModuleInfo.intf != NULL) { \
				hashtable_UtModuleInfo.intf->Trace((void *)NULL, &hashtable_UtModuleInfo, (UT_SPECIAL_ASSERTION | (1u << 8) | hashtable_UtActive[1]), "\377\4\377", __FILE__, __LINE__, UT_STR((!(P1)))); \
				Trace_Unreachable(); \
			} else { \
				fprintf(stderr, "** ASSERTION FAILED ** hashtable.1 at %s:%d Assert_hashTable_false%s\n", __FILE__, __LINE__, UT_STR((!(P1)))); \
			} \
		}} \
	} while(0)
#else
#define Assert_hashTable_false(P1)   /* tracepoint name: hashtable.1 */
#endif

#if UT_TRACE_OVERHEAD >= 1
#define Assert_hashTable_unreachable() do { /* tracepoint name: hashtable.2 */ \
	if ((unsigned char) hashtable_UtActive[2] != 0){ \
		if ((FALSE)) { /* assertion satisfied */ } else { \
			if (hashtable_UtModuleInfo.intf != NULL) { \
				hashtable_UtModuleInfo.intf->Trace((void *)NULL, &hashtable_UtModuleInfo, (UT_SPECIAL_ASSERTION | (2u << 8) | hashtable_UtActive[2]), "\377\4\377", __FILE__, __LINE__, UT_STR(((FALSE)))); \
				Trace_Unreachable(); \
			} else { \
				fprintf(stderr, "** ASSERTION FAILED ** hashtable.2 at %s:%d Assert_hashTable_unreachable%s\n", __FILE__, __LINE__, UT_STR(((FALSE)))); \
			} \
		}} \
	} while(0)
#else
#define Assert_hashTable_unreachable()   /* tracepoint name: hashtable.2 */
#endif

#if UT_TRACE_OVERHEAD >= 1
#define Trc_hashTable_listToTree_Entry(P1, P2, P3, P4) do { /* tracepoint name: hashtable.3 */ \
	if ((unsigned char) hashtable_UtActive[3] != 0){ \
		hashtable_UtModuleInfo.intf->Trace((void *)NULL, &hashtable_UtModuleInfo, ((3u << 8) | hashtable_UtActive[3]), "\377\6\6\6", P1, P2, P3, P4);} \
	} while(0)
#else
#define Trc_hashTable_listToTree_Entry(P1, P2, P3, P4)   /* tracepoint name: hashtable.3 */
#endif

#if UT_TRACE_OVERHEAD >= 1
#define Trc_hashTable_listToTree_Exit(P1, P2) do { /* tracepoint name: hashtable.4 */ \
	if ((unsigned char) hashtable_UtActive[4] != 0){ \
		hashtable_UtModuleInfo.intf->Trace((void *)NULL, &hashtable_UtModuleInfo, ((4u << 8) | hashtable_UtActive[4]), "\6\6", P1, P2);} \
	} while(0)
#else
#define Trc_hashTable_listToTree_Exit(P1, P2)   /* tracepoint name: hashtable.4 */
#endif

extern UtModuleInfo hashtable_UtModuleInfo;
extern unsigned char hashtable_UtActive[];

#ifndef UT_MODULE_INFO
#define UT_MODULE_INFO hashtable_UtModuleInfo
#endif /* UT_MODULE_INFO */

#ifndef UT_ACTIVE
#define UT_ACTIVE hashtable_UtActive
#endif /* UT_ACTIVE */

#ifdef __cplusplus
} /* extern "C" */
#endif
#endif /* UTE_HASHTABLE_MODULE_HEADER */
/*
 * End of file
 */
