/* File generated by tracegen, do not edit */
#include "ut_avl.h"



#define UT_TRACE_VERSION 8
UtTraceVersionInfo avl_UtTraceVersionInfo = {UT_TRACE_VERSION};
#if defined(UT_TRACE_ENABLED_IN_BUILD)
unsigned char avl_UtActive[21] = { 
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1};

unsigned char avl_UtLevels[21] = { 
	3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,1};


int32_t avl_tpids5[] = {

	19,20	};

UtGroupDetails avl_group5 = {
	(char *)"Assertion",
	2,
	avl_tpids5,
	NULL};

UtGroupDetails avl_group4 = {
	(char *)"Debug",
	0,
	NULL,
	&avl_group5};

UtGroupDetails avl_group3 = {
	(char *)"Exception",
	0,
	NULL,
	&avl_group4};

UtGroupDetails avl_group2 = {
	(char *)"Event",
	0,
	NULL,
	&avl_group3};
int32_t avl_tpids1[] = {

	1,2,4,6,8,10,11,12,14,16,17,18	};

UtGroupDetails avl_group1 = {
	(char *)"Exit",
	12,
	avl_tpids1,
	&avl_group2};
int32_t avl_tpids0[] = {

	0,3,5,7,9,13,15	};

UtGroupDetails avl_group0 = {
	(char *)"Entry",
	7,
	avl_tpids0,
	&avl_group1};
UtModuleInfo avl_UtModuleInfo = {(char*) "avl", 3, 21, 0, avl_UtActive , NULL, NULL, &avl_UtTraceVersionInfo, (char*) "J9TraceFormat.dat", avl_UtLevels, &avl_group0, NULL, NULL, 0, 0};

#else
unsigned char avl_UtActive[1];
UtModuleInfo avl_UtModuleInfo = {(char*) "avl", 3, 0, 0, NULL, NULL, NULL, &avl_UtTraceVersionInfo, (char*) "J9TraceFormat.dat", NULL, NULL, NULL, NULL, 0, 0};

#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */

#if defined(UT_DIRECT_TRACE_REGISTRATION)

/* function to register with trace engine and configure current module */
int32_t
registeravlWithTrace(UtInterface *utIntf, UtModuleInfo * containerModule)
{
	I_32 rc = 0;

#if defined(UT_TRACE_ENABLED_IN_BUILD)

	avl_UtModuleInfo.containerModule = containerModule;

	if( utIntf == NULL ) {
		rc = -1;
	}

	if (rc == 0) {
		utIntf->module->TraceInit(NULL, &avl_UtModuleInfo);
	}

#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

/* function to deregister with trace engine and configure current module */
int32_t
deregisteravlWithTrace(UtInterface *utIntf)
{
	I_32 rc = 0;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	if( utIntf == NULL ) {
		rc = -1;
	}

	if (rc == 0) {
		utIntf->module->TraceTerm(NULL, &avl_UtModuleInfo);
	}
#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

#else /* defined(UT_DIRECT_TRACE_REGISTRATION) */

/* function to register with trace engine and configure current module */
int32_t
registeravlWithTrace(JavaVM *vm, UtModuleInfo * containerModule)
{
	I_32 rc = JNI_OK;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	UtInterface *utIntf;

	avl_UtModuleInfo.containerModule = containerModule;

	if( vm != NULL ) {
		rc = (*vm)->GetEnv(vm, (void**)&utIntf, UTE_VERSION_1_1);
	} else {
		rc = JNI_ERR;
	}

	if (rc == JNI_OK) {
		utIntf->module->TraceInit(NULL, &avl_UtModuleInfo);
	}

#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

/* function to deregister with trace engine and configure current module */
int32_t
deregisteravlWithTrace(JavaVM *vm)
{
	I_32 rc = JNI_OK;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	UtInterface *utIntf;

	if( vm != NULL ) {
		rc = (*vm)->GetEnv(vm, (void**)&utIntf, UTE_VERSION_1_1);
	} else {
		rc = JNI_ERR;
	}

	if (rc == JNI_OK) {
		utIntf->module->TraceTerm(NULL, &avl_UtModuleInfo);
	}
#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

#endif /* defined(UT_DIRECT_TRACE_REGISTRATION) */

/* End of generated file */
