/* File generated by tracegen, do not edit */
#include "ut_omr_test.h"



#define UT_TRACE_VERSION 8
UtTraceVersionInfo omr_test_UtTraceVersionInfo = {UT_TRACE_VERSION};
#if defined(UT_TRACE_ENABLED_IN_BUILD)
unsigned char omr_test_UtActive[6] = { 
	0,0,0,0,0,0};

unsigned char omr_test_UtLevels[6] = { 
	1,1,1,1,1,1};


int32_t omr_test_tpids5[] = {

	0,1,2,3,4	};

UtGroupDetails omr_test_group5 = {
	(char *)"testset1",
	5,
	omr_test_tpids5,
	NULL};

UtGroupDetails omr_test_group4 = {
	(char *)"Debug",
	0,
	NULL,
	&omr_test_group5};

UtGroupDetails omr_test_group3 = {
	(char *)"Exception",
	0,
	NULL,
	&omr_test_group4};
int32_t omr_test_tpids2[] = {

	0,1,2,3,4,5	};

UtGroupDetails omr_test_group2 = {
	(char *)"Event",
	6,
	omr_test_tpids2,
	&omr_test_group3};

UtGroupDetails omr_test_group1 = {
	(char *)"Exit",
	0,
	NULL,
	&omr_test_group2};

UtGroupDetails omr_test_group0 = {
	(char *)"Entry",
	0,
	NULL,
	&omr_test_group1};
UtModuleInfo omr_test_UtModuleInfo = {(char*) "omr_test", 8, 6, 0, omr_test_UtActive , NULL, NULL, &omr_test_UtTraceVersionInfo, (char*) "OMRTestTraceFormat.dat", omr_test_UtLevels, &omr_test_group0, NULL, NULL, 0, 0};

#else
unsigned char omr_test_UtActive[1];
UtModuleInfo omr_test_UtModuleInfo = {(char*) "omr_test", 8, 0, 0, NULL, NULL, NULL, &omr_test_UtTraceVersionInfo, (char*) "OMRTestTraceFormat.dat", NULL, NULL, NULL, NULL, 0, 0};

#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */

#if defined(UT_DIRECT_TRACE_REGISTRATION)

/* function to register with trace engine and configure current module */
int32_t
registeromr_testWithTrace(UtInterface *utIntf, UtModuleInfo * containerModule)
{
	I_32 rc = 0;

#if defined(UT_TRACE_ENABLED_IN_BUILD)

	omr_test_UtModuleInfo.containerModule = containerModule;

	if( utIntf == NULL ) {
		rc = -1;
	}

	if (rc == 0) {
		utIntf->module->TraceInit(NULL, &omr_test_UtModuleInfo);
	}

#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

/* function to deregister with trace engine and configure current module */
int32_t
deregisteromr_testWithTrace(UtInterface *utIntf)
{
	I_32 rc = 0;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	if( utIntf == NULL ) {
		rc = -1;
	}

	if (rc == 0) {
		utIntf->module->TraceTerm(NULL, &omr_test_UtModuleInfo);
	}
#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

#else /* defined(UT_DIRECT_TRACE_REGISTRATION) */

/* function to register with trace engine and configure current module */
int32_t
registeromr_testWithTrace(JavaVM *vm, UtModuleInfo * containerModule)
{
	I_32 rc = JNI_OK;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	UtInterface *utIntf;

	omr_test_UtModuleInfo.containerModule = containerModule;

	if( vm != NULL ) {
		rc = (*vm)->GetEnv(vm, (void**)&utIntf, UTE_VERSION_1_1);
	} else {
		rc = JNI_ERR;
	}

	if (rc == JNI_OK) {
		utIntf->module->TraceInit(NULL, &omr_test_UtModuleInfo);
	}

#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

/* function to deregister with trace engine and configure current module */
int32_t
deregisteromr_testWithTrace(JavaVM *vm)
{
	I_32 rc = JNI_OK;

#if defined(UT_TRACE_ENABLED_IN_BUILD)
	UtInterface *utIntf;

	if( vm != NULL ) {
		rc = (*vm)->GetEnv(vm, (void**)&utIntf, UTE_VERSION_1_1);
	} else {
		rc = JNI_ERR;
	}

	if (rc == JNI_OK) {
		utIntf->module->TraceTerm(NULL, &omr_test_UtModuleInfo);
	}
#else
	/* trace not present in build - NOOP */
#endif /* defined(UT_TRACE_ENABLED_IN_BUILD) */
	return rc;
}

#endif /* defined(UT_DIRECT_TRACE_REGISTRATION) */

/* End of generated file */
